server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:${DB_TYPE:postgresql}://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:ceposto2021}
  jpa: 
    properties:
      hibernate:
        ddl-auto: update